### ISSUE TITLE
Uploaded SVGs underlined

### ISSUE THREAD

**Issue by milse113** [dougrich/conscripter#24]
**Describe the bug**
Uploaded SVGs get a big black bar at the bottom of them, which stays in the font when downloaded

**To Reproduce**
Upload SVG
https://ibb.co/mCty8xg <- The SVGs uploaded. The black bar was not in any of the original files

**Context**
- Firefox 74.0
- macOS 10.15.3

**Comment by dougrich** [comment]
Any chance you can send me the original SVGs that you uploaded to poke at?

**Comment by milse113** [comment]
https://cdn.discordapp.com/attachments/544289143606214660/695273035128766484/Jamiidi.1.zip

No problem!

**Comment by dougrich** [comment]
Thanks for uploading the SVG - there's an element that has a fill opacity of 0 that I'm picking up. Let me do some tweaking locally to see if I can fix it (it shouldn't be read in) but if you want a temporary workaround, you can remove that element.

Out of curiosity, what editor are you using for this SVG?

**Comment by dougrich** [comment]
Deployed the fix - let me know if you're seeing the issue still

**Comment by milse113** [comment]
Figured I'd let you know about #26 here since its a similar issue
