### ISSUE TITLE
Uploaded SVGs tearing

### ISSUE THREAD

**Issue by milse113** [dougrich/conscripter#26]
**Describe the bug**
Hard to explain. Uploading the attached SVGs causes some weird rendering stuff

**To Reproduce**
https://filebin.net/v8kbyoxjyelrpq4h
Upload SVGs in this Zip

**Desktop (please complete the following information):**
 - See previous issue

**Comment by dougrich** [comment]
Looking into this - thanks for the examples, I can see why it was a little hard to explain. Reviewing:

0 - stem on the side is too short
1 - I'm not sure if there was an issue with this one - could you provide a screenshot of what you were seeing?
2 - stem is instead turned into a holepunch in the loop
3 - numbers gone wrong/null island
4 - 3 but mirrored
5 - holepunch/fill rule + truncated stem
6 - numbers gone wrong/null island
7 - holepunch/fill rule

Generally the fill rule seems to be the issue. As a workaround you can try unioning the paths in your editor and then trying the upload - but these files should work. I won't be able to look into these until later today unfortunately, but will update here when I've got fixes in place.

Thank you for the feedback & bug reporting!

**Comment by dougrich** [comment]
Found the fix. Will update when it is deployed - weird handling of zero coordinates caused all of the issues.

**Comment by dougrich** [comment]
Should be deployed now!
