### ISSUE TITLE
Reordering by dragging doesn't properly update substitution order in preview

### ISSUE THREAD

**Issue by ZetDude** [dougrich/conscripter#8]
**Describe the bug**
Reordering by dragging doesn't properly update substitution order in preview

**To Reproduce**
1. Create two characters that may overlap i.e. "ph" and "h"
2. Create "h" before "ph"
3. Drag "ph" ahead of "h"
4. writing "ph" in the preview comes out as "p" and "h" glyphs, separately

**Expected behavior**
Updated order ("ph" becomes "ph" glyph)

**Screenshots**
![image](https://user-images.githubusercontent.com/31309189/56097597-40e60a80-5eff-11e9-826b-7d8f50b94d45.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 74

**Additional context**
I am aware of the arrows but it took me a bit to see them, dragging is more intuitive, and its easier over long distances
PLUS, issue #2 makes it hard

and also, saving and loading the json fixes this

**Comment by dougrich** [comment]
That's strange that saving and loading the json fixes it - would you mind adding a copy of the json so I can test it out?

Thanks for the bug report!

**Comment by dougrich** [comment]
Thanks for reporting this. This should be resolved in 0.1.1, which has been deployed.

I'm going to close this out for now, but feel free to re-open if you see this issue again.
